import { z } from 'zod'

const namePattern = /^[A-Za-zÁÉÍÓÚáéíóúÑñÜü\s]+$/

export const affiliationSchema = z.object({
  radicadoDia: z.string().regex(/^\d{2}$/, 'Día inválido'),
  radicadoMes: z.string().regex(/^\d{2}$/, 'Mes inválido'),
  radicadoAnio: z.string().regex(/^\d{4}$/, 'Año inválido'),
  tipoTramite: z.enum(['Afiliacion', 'ReporteNovedades']),
  tipoAfiliacion: z.enum(['CotizanteCabezaFamilia', 'BeneficiarioAdicional', 'Colectiva', 'DeOficio']),
  contribucionSolidaria: z.enum(['Si', 'No']),
  tipoAfiliado: z.enum(['Cotizante', 'Beneficiario', 'CabezaFamilia', 'AfiliadoAdicional']),
  tipoCotizante: z.enum(['Dependiente', 'Independiente', 'Pensionado']),
  codigoEps: z
    .string()
    .min(3, 'Mínimo 3 dígitos')
    .regex(/^\d+$/, 'Solo se permiten números'),
  primerApellido: z
    .string()
    .min(2, 'Ingrese al menos 2 caracteres')
    .regex(namePattern, 'Solo se permiten letras y espacios'),
  segundoApellido: z
    .string()
    .min(2, 'Ingrese al menos 2 caracteres')
    .regex(namePattern, 'Solo se permiten letras y espacios'),
  primerNombre: z
    .string()
    .min(2, 'Ingrese al menos 2 caracteres')
    .regex(namePattern, 'Solo se permiten letras y espacios'),
  segundoNombre: z
    .string()
    .min(2, 'Ingrese al menos 2 caracteres')
    .regex(namePattern, 'Solo se permiten letras y espacios'),
  tipoDocumento: z.enum(['CC', 'TI', 'CE', 'PA']),
  numeroDocumento: z
    .string()
    .min(6, 'Debe tener mínimo 6 dígitos')
    .regex(/^\d+$/, 'Solo se permiten números'),
  sexoBiologico: z.enum(['F', 'M']),
  sexoIdentificacion: z.enum(['F', 'M', 'T', 'NB', 'Otro']),
  sexoIdentificacionCual: z.string().optional(),
  nacionalidad: z.string().min(2, 'Ingrese nacionalidad'),
  nacimientoPais: z.string().min(2, 'Ingrese país'),
  nacimientoDepartamento: z.string().min(2, 'Ingrese departamento'),
  nacimientoMunicipio: z.string().min(2, 'Ingrese municipio'),
  fechaNacimientoDia: z.string().regex(/^\d{2}$/, 'Día inválido'),
  fechaNacimientoMes: z.string().regex(/^\d{2}$/, 'Mes inválido'),
  fechaNacimientoAnio: z.string().regex(/^\d{4}$/, 'Año inválido'),
  etnia: z.string().optional(),
  comunidad: z.string().optional(),
  discapacidad: z.enum(['Si', 'No']),
  categoriaDiscapacidad: z.string().optional(),
  encuestaSisben: z.enum(['Si', 'No']),
  clasificacionSisbenNivel: z.string().optional(),
  clasificacionSisbenGrupo: z.string().optional(),
  grupoPoblacionEspecial: z.string().optional(),
  administradoraRiesgosLaborales: z.string().optional(),
  administradoraPensiones: z.string().optional(),
  ingresoBaseCotizacion: z.string().optional(),
  tarifaContribucionSolidaria: z.string().optional(),
  residenciaDireccion: z.string().optional(),
  telefonoFijo: z.string().optional(),
  departamentoResidencia: z.string().optional(),
  municipioDistrito: z.string().optional(),
  localidadComuna: z.string().optional(),
  zonaResidencia: z.enum(['CabeceraMunicipal', 'CentroPoblado', 'RuralDisperso']),
  correo: z.string().email('Correo electrónico inválido'),
  telefono: z
    .string()
    .min(7, 'Debe tener mínimo 7 dígitos')
    .regex(/^\d+$/, 'Solo se permiten números'),
  conyugePrimerApellido: z.string().optional(),
  conyugeSegundoApellido: z.string().optional(),
  conyugePrimerNombre: z.string().optional(),
  conyugeSegundoNombre: z.string().optional(),
  conyugeTipoDocumento: z.enum(['CC', 'TI', 'CE', 'PA']),
  conyugeNumeroDocumento: z.string().optional(),
  conyugeSexoBiologico: z.enum(['F', 'M']),
  conyugeSexoIdentificacion: z.enum(['F', 'M', 'T', 'NB', 'Otro']),
  conyugeSexoIdentificacionCual: z.string().optional(),
  conyugeNacionalidad: z.string().optional(),
  conyugeNacimientoPais: z.string().optional(),
  conyugeNacimientoDepartamento: z.string().optional(),
  conyugeNacimientoMunicipio: z.string().optional(),
  conyugeFechaNacimientoDia: z.string().optional(),
  conyugeFechaNacimientoMes: z.string().optional(),
  conyugeFechaNacimientoAnio: z.string().optional(),
  beneficiarioB1PrimerApellido: z.string().optional(),
  beneficiarioB1SegundoApellido: z.string().optional(),
  beneficiarioB1PrimerNombre: z.string().optional(),
  beneficiarioB1SegundoNombre: z.string().optional(),
  beneficiarioB1TipoDocumento: z.string().optional(),
  beneficiarioB1NumeroDocumento: z.string().optional(),
  beneficiarioB1Nacionalidad: z.string().optional(),
  beneficiarioB1SexoBiologico: z.string().optional(),
  beneficiarioB1SexoIdentificacion: z.string().optional(),
  beneficiarioB1SexoIdentificacionCual: z.string().optional(),
  beneficiarioB1PaisBirth: z.string().optional(),
  beneficiarioB1DepartamentoBirth: z.string().optional(),
  beneficiarioB1MunicipioBirth: z.string().optional(),
  beneficiarioB1FechaNacimientoDia: z.string().optional(),
  beneficiarioB1FechaNacimientoMes: z.string().optional(),
  beneficiarioB1FechaNacimientoAnio: z.string().optional(),
  beneficiarioB2PrimerApellido: z.string().optional(),
  beneficiarioB2SegundoApellido: z.string().optional(),
  beneficiarioB2PrimerNombre: z.string().optional(),
  beneficiarioB2SegundoNombre: z.string().optional(),
  beneficiarioB2TipoDocumento: z.string().optional(),
  beneficiarioB2NumeroDocumento: z.string().optional(),
  beneficiarioB2Nacionalidad: z.string().optional(),
  beneficiarioB2SexoBiologico: z.string().optional(),
  beneficiarioB2SexoIdentificacion: z.string().optional(),
  beneficiarioB2SexoIdentificacionCual: z.string().optional(),
  beneficiarioB2PaisBirth: z.string().optional(),
  beneficiarioB2DepartamentoBirth: z.string().optional(),
  beneficiarioB2MunicipioBirth: z.string().optional(),
  beneficiarioB2FechaNacimientoDia: z.string().optional(),
  beneficiarioB2FechaNacimientoMes: z.string().optional(),
  beneficiarioB2FechaNacimientoAnio: z.string().optional(),
  beneficiarioB3PrimerApellido: z.string().optional(),
  beneficiarioB3SegundoApellido: z.string().optional(),
  beneficiarioB3PrimerNombre: z.string().optional(),
  beneficiarioB3SegundoNombre: z.string().optional(),
  beneficiarioB3TipoDocumento: z.string().optional(),
  beneficiarioB3NumeroDocumento: z.string().optional(),
  beneficiarioB3Nacionalidad: z.string().optional(),
  beneficiarioB3SexoBiologico: z.string().optional(),
  beneficiarioB3SexoIdentificacion: z.string().optional(),
  beneficiarioB3SexoIdentificacionCual: z.string().optional(),
  beneficiarioB3PaisBirth: z.string().optional(),
  beneficiarioB3DepartamentoBirth: z.string().optional(),
  beneficiarioB3MunicipioBirth: z.string().optional(),
  beneficiarioB3FechaNacimientoDia: z.string().optional(),
  beneficiarioB3FechaNacimientoMes: z.string().optional(),
  beneficiarioB3FechaNacimientoAnio: z.string().optional(),
  beneficiarioB4PrimerApellido: z.string().optional(),
  beneficiarioB4SegundoApellido: z.string().optional(),
  beneficiarioB4PrimerNombre: z.string().optional(),
  beneficiarioB4SegundoNombre: z.string().optional(),
  beneficiarioB4TipoDocumento: z.string().optional(),
  beneficiarioB4NumeroDocumento: z.string().optional(),
  beneficiarioB4Nacionalidad: z.string().optional(),
  beneficiarioB4SexoBiologico: z.string().optional(),
  beneficiarioB4SexoIdentificacion: z.string().optional(),
  beneficiarioB4SexoIdentificacionCual: z.string().optional(),
  beneficiarioB4PaisBirth: z.string().optional(),
  beneficiarioB4DepartamentoBirth: z.string().optional(),
  beneficiarioB4MunicipioBirth: z.string().optional(),
  beneficiarioB4FechaNacimientoDia: z.string().optional(),
  beneficiarioB4FechaNacimientoMes: z.string().optional(),
  beneficiarioB4FechaNacimientoAnio: z.string().optional(),
  beneficiarioB5PrimerApellido: z.string().optional(),
  beneficiarioB5SegundoApellido: z.string().optional(),
  beneficiarioB5PrimerNombre: z.string().optional(),
  beneficiarioB5SegundoNombre: z.string().optional(),
  beneficiarioB5TipoDocumento: z.string().optional(),
  beneficiarioB5NumeroDocumento: z.string().optional(),
  beneficiarioB5Nacionalidad: z.string().optional(),
  beneficiarioB5SexoBiologico: z.string().optional(),
  beneficiarioB5SexoIdentificacion: z.string().optional(),
  beneficiarioB5SexoIdentificacionCual: z.string().optional(),
  beneficiarioB5PaisBirth: z.string().optional(),
  beneficiarioB5DepartamentoBirth: z.string().optional(),
  beneficiarioB5MunicipioBirth: z.string().optional(),
  beneficiarioB5FechaNacimientoDia: z.string().optional(),
  beneficiarioB5FechaNacimientoMes: z.string().optional(),
  beneficiarioB5FechaNacimientoAnio: z.string().optional(),
  beneficiarioB1Departamento: z.string().optional(),
  beneficiarioB1Municipio: z.string().optional(),
  beneficiarioB1Localidad: z.string().optional(),
  beneficiarioB1Zona: z.string().optional(),
  beneficiarioB1Direccion: z.string().optional(),
  beneficiarioB1TelefonoFijo: z.string().optional(),
  beneficiarioB1TelefonoCelular: z.string().optional(),
  beneficiarioB1Correo: z.string().optional(),
  beneficiarioB2Departamento: z.string().optional(),
  beneficiarioB2Municipio: z.string().optional(),
  beneficiarioB2Localidad: z.string().optional(),
  beneficiarioB2Zona: z.string().optional(),
  beneficiarioB2Direccion: z.string().optional(),
  beneficiarioB2TelefonoFijo: z.string().optional(),
  beneficiarioB2TelefonoCelular: z.string().optional(),
  beneficiarioB2Correo: z.string().optional(),
  beneficiarioB3Departamento: z.string().optional(),
  beneficiarioB3Municipio: z.string().optional(),
  beneficiarioB3Localidad: z.string().optional(),
  beneficiarioB3Zona: z.string().optional(),
  beneficiarioB3Direccion: z.string().optional(),
  beneficiarioB3TelefonoFijo: z.string().optional(),
  beneficiarioB3TelefonoCelular: z.string().optional(),
  beneficiarioB3Correo: z.string().optional(),
  beneficiarioB4Departamento: z.string().optional(),
  beneficiarioB4Municipio: z.string().optional(),
  beneficiarioB4Localidad: z.string().optional(),
  beneficiarioB4Zona: z.string().optional(),
  beneficiarioB4Direccion: z.string().optional(),
  beneficiarioB4TelefonoFijo: z.string().optional(),
  beneficiarioB4TelefonoCelular: z.string().optional(),
  beneficiarioB4Correo: z.string().optional(),
  beneficiarioB5Departamento: z.string().optional(),
  beneficiarioB5Municipio: z.string().optional(),
  beneficiarioB5Localidad: z.string().optional(),
  beneficiarioB5Zona: z.string().optional(),
  beneficiarioB5Direccion: z.string().optional(),
  beneficiarioB5TelefonoFijo: z.string().optional(),
  beneficiarioB5TelefonoCelular: z.string().optional(),
  beneficiarioB5Correo: z.string().optional(),
  regimen: z.enum(['Contributivo', 'Subsidiado']),
})

export type AffiliationFormData = z.infer<typeof affiliationSchema>

export const defaultValues: AffiliationFormData = {
  radicadoDia: '',
  radicadoMes: '',
  radicadoAnio: '',
  tipoTramite: 'Afiliacion',
  tipoAfiliacion: 'CotizanteCabezaFamilia',
  contribucionSolidaria: 'No',
  tipoAfiliado: 'Cotizante',
  tipoCotizante: 'Dependiente',
  codigoEps: '',
  primerApellido: '',
  segundoApellido: '',
  primerNombre: '',
  segundoNombre: '',
  tipoDocumento: 'CC',
  numeroDocumento: '',
  sexoBiologico: 'F',
  sexoIdentificacion: 'F',
  sexoIdentificacionCual: '',
  nacionalidad: 'Colombiana',
  nacimientoPais: '',
  nacimientoDepartamento: '',
  nacimientoMunicipio: '',
  fechaNacimientoDia: '',
  fechaNacimientoMes: '',
  fechaNacimientoAnio: '',
  etnia: '',
  comunidad: '',
  discapacidad: 'No',
  categoriaDiscapacidad: '',
  encuestaSisben: 'No',
  clasificacionSisbenNivel: '',
  clasificacionSisbenGrupo: '',
  grupoPoblacionEspecial: '',
  administradoraRiesgosLaborales: '',
  administradoraPensiones: '',
  ingresoBaseCotizacion: '',
  tarifaContribucionSolidaria: '',
  residenciaDireccion: '',
  telefonoFijo: '',
  departamentoResidencia: '',
  municipioDistrito: '',
  localidadComuna: '',
  zonaResidencia: 'CabeceraMunicipal',
  correo: '',
  telefono: '',
  conyugePrimerApellido: '',
  conyugeSegundoApellido: '',
  conyugePrimerNombre: '',
  conyugeSegundoNombre: '',
  conyugeTipoDocumento: 'CC',
  conyugeNumeroDocumento: '',
  conyugeSexoBiologico: 'F',
  conyugeSexoIdentificacion: 'F',
  conyugeSexoIdentificacionCual: '',
  conyugeNacionalidad: '',
  conyugeNacimientoPais: '',
  conyugeNacimientoDepartamento: '',
  conyugeNacimientoMunicipio: '',
  conyugeFechaNacimientoDia: '',
  conyugeFechaNacimientoMes: '',
  conyugeFechaNacimientoAnio: '',
  beneficiarioB1PrimerApellido: '',
  beneficiarioB1SegundoApellido: '',
  beneficiarioB1PrimerNombre: '',
  beneficiarioB1SegundoNombre: '',
  beneficiarioB1TipoDocumento: '',
  beneficiarioB1NumeroDocumento: '',
  beneficiarioB1Nacionalidad: '',
  beneficiarioB1SexoBiologico: '',
  beneficiarioB1SexoIdentificacion: '',
  beneficiarioB1SexoIdentificacionCual: '',
  beneficiarioB1PaisBirth: '',
  beneficiarioB1DepartamentoBirth: '',
  beneficiarioB1MunicipioBirth: '',
  beneficiarioB1FechaNacimientoDia: '',
  beneficiarioB1FechaNacimientoMes: '',
  beneficiarioB1FechaNacimientoAnio: '',
  beneficiarioB2PrimerApellido: '',
  beneficiarioB2SegundoApellido: '',
  beneficiarioB2PrimerNombre: '',
  beneficiarioB2SegundoNombre: '',
  beneficiarioB2TipoDocumento: '',
  beneficiarioB2NumeroDocumento: '',
  beneficiarioB2Nacionalidad: '',
  beneficiarioB2SexoBiologico: '',
  beneficiarioB2SexoIdentificacion: '',
  beneficiarioB2SexoIdentificacionCual: '',
  beneficiarioB2PaisBirth: '',
  beneficiarioB2DepartamentoBirth: '',
  beneficiarioB2MunicipioBirth: '',
  beneficiarioB2FechaNacimientoDia: '',
  beneficiarioB2FechaNacimientoMes: '',
  beneficiarioB2FechaNacimientoAnio: '',
  beneficiarioB3PrimerApellido: '',
  beneficiarioB3SegundoApellido: '',
  beneficiarioB3PrimerNombre: '',
  beneficiarioB3SegundoNombre: '',
  beneficiarioB3TipoDocumento: '',
  beneficiarioB3NumeroDocumento: '',
  beneficiarioB3Nacionalidad: '',
  beneficiarioB3SexoBiologico: '',
  beneficiarioB3SexoIdentificacion: '',
  beneficiarioB3SexoIdentificacionCual: '',
  beneficiarioB3PaisBirth: '',
  beneficiarioB3DepartamentoBirth: '',
  beneficiarioB3MunicipioBirth: '',
  beneficiarioB3FechaNacimientoDia: '',
  beneficiarioB3FechaNacimientoMes: '',
  beneficiarioB3FechaNacimientoAnio: '',
  beneficiarioB4PrimerApellido: '',
  beneficiarioB4SegundoApellido: '',
  beneficiarioB4PrimerNombre: '',
  beneficiarioB4SegundoNombre: '',
  beneficiarioB4TipoDocumento: '',
  beneficiarioB4NumeroDocumento: '',
  beneficiarioB4Nacionalidad: '',
  beneficiarioB4SexoBiologico: '',
  beneficiarioB4SexoIdentificacion: '',
  beneficiarioB4SexoIdentificacionCual: '',
  beneficiarioB4PaisBirth: '',
  beneficiarioB4DepartamentoBirth: '',
  beneficiarioB4MunicipioBirth: '',
  beneficiarioB4FechaNacimientoDia: '',
  beneficiarioB4FechaNacimientoMes: '',
  beneficiarioB4FechaNacimientoAnio: '',
  beneficiarioB5PrimerApellido: '',
  beneficiarioB5SegundoApellido: '',
  beneficiarioB5PrimerNombre: '',
  beneficiarioB5SegundoNombre: '',
  beneficiarioB5TipoDocumento: '',
  beneficiarioB5NumeroDocumento: '',
  beneficiarioB5Nacionalidad: '',
  beneficiarioB5SexoBiologico: '',
  beneficiarioB5SexoIdentificacion: '',
  beneficiarioB5SexoIdentificacionCual: '',
  beneficiarioB5PaisBirth: '',
  beneficiarioB5DepartamentoBirth: '',
  beneficiarioB5MunicipioBirth: '',
  beneficiarioB5FechaNacimientoDia: '',
  beneficiarioB5FechaNacimientoMes: '',
  beneficiarioB5FechaNacimientoAnio: '',
  beneficiarioB1Departamento: '',
  beneficiarioB1Municipio: '',
  beneficiarioB1Localidad: '',
  beneficiarioB1Zona: '',
  beneficiarioB1Direccion: '',
  beneficiarioB1TelefonoFijo: '',
  beneficiarioB1TelefonoCelular: '',
  beneficiarioB1Correo: '',
  beneficiarioB2Departamento: '',
  beneficiarioB2Municipio: '',
  beneficiarioB2Localidad: '',
  beneficiarioB2Zona: '',
  beneficiarioB2Direccion: '',
  beneficiarioB2TelefonoFijo: '',
  beneficiarioB2TelefonoCelular: '',
  beneficiarioB2Correo: '',
  beneficiarioB3Departamento: '',
  beneficiarioB3Municipio: '',
  beneficiarioB3Localidad: '',
  beneficiarioB3Zona: '',
  beneficiarioB3Direccion: '',
  beneficiarioB3TelefonoFijo: '',
  beneficiarioB3TelefonoCelular: '',
  beneficiarioB3Correo: '',
  beneficiarioB4Departamento: '',
  beneficiarioB4Municipio: '',
  beneficiarioB4Localidad: '',
  beneficiarioB4Zona: '',
  beneficiarioB4Direccion: '',
  beneficiarioB4TelefonoFijo: '',
  beneficiarioB4TelefonoCelular: '',
  beneficiarioB4Correo: '',
  beneficiarioB5Departamento: '',
  beneficiarioB5Municipio: '',
  beneficiarioB5Localidad: '',
  beneficiarioB5Zona: '',
  beneficiarioB5Direccion: '',
  beneficiarioB5TelefonoFijo: '',
  beneficiarioB5TelefonoCelular: '',
  beneficiarioB5Correo: '',
  regimen: 'Contributivo',
}
